version: "3"
services:
  spring-milsestone: 
    image: spring-milestone
    restart: always
    build: .
    ports:
      - 9090:8080
    environment:
       MYSQL_HOST: mysqlcas
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_PORT: 3306
       
  mysqlms: 
    container_name: mysqlcs
    image: mysql:5.6
    ports:
      - 3308:3306
    environment:
        MYSQL_DATABASE: css
        MYSQL_ROOT_PASSWORD: root